version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: urlshortener-app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --proxy-headers
    volumes:
      - .:/app   # live code reload in dev
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db:5432/url_db
    depends_on:
      - db

volumes:
  pgdata:
