name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: url_db
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U user" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5
    env:
      DATABASE_URL: postgresql+asyncpg://user:password@localhost:5432/url_db
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: pytest
