name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: url_db
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U user -d url_db" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5
    
    env:
      DATABASE_URL: postgresql+asyncpg://user:password@localhost:5432/url_db
    
    steps:
      - uses: actions/checkout@v4  # Updated to v4
      - uses: actions/setup-python@v5  # Updated to v5
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create __init__.py files
        run: |
          touch app/__init__.py
          touch tests/__init__.py
      
      - name: Run database migrations
        run: alembic upgrade head
      
      - name: Run tests
        run: pytest tests/ -v --tb=short
      
      - name: Run tests with coverage (optional)
        run: |
          pip install pytest-cov
          pytest tests/ --cov=app --cov-report=xml
      
      - name: Upload coverage to Codecov (optional)
        uses: codecov/codecov-action@v3
        if: success()
        with:
          file: ./coverage.xml